; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
build_flags = 
    -DCONFIG_PM_ENABLE=0
    -DCONFIG_ESP32C3_DEFAULT_CPU_FREQ_160=1
    -DCONFIG_FREERTOS_UNICORE=1
    -DCONFIG_FREERTOS_HZ=1000
    ; These are critical for disabling power management:
    -DCONFIG_ESP32C3_RTC_CLK_CAL_CYCLES=1024
    -DCONFIG_ESP_PM_POWER_DOWN_CPU_IN_LIGHT_SLEEP=n
    -DCONFIG_ESP_SYSTEM_PD_FLASH=n
    -DCONFIG_ESP_SLEEP_POWER_DOWN_FLASH=n
    ; Disable brownout detector (can cause resets)
    -DBOARD_HAS_PSRAM=n
    -DCONFIG_ESP32C3_BROWNOUT_DET=n

lib_deps = 
    earlephilhower/ESP8266Audio@1.9.7

board_build.f_cpu = 160000000L
upload_speed = 921600
monitor_filters = direct
